# Generated by Django 4.1.5 on 2023-01-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address', models.JSONField(default=dict)),
                ('send_update', models.BooleanField(blank=True, null=True)),
                ('photo', models.FileField(upload_to='profile')),
            ],
        ),
    ]
