# Generated by Django 4.1.5 on 2023-01-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.AlterField(
            model_name='employee',
            name='send_update',
            field=models.BooleanField(default=False),
        ),
    ]
